Issue388 - Create language google sheet
Hyperobjekt/seda-map pull request #394
Opened 2021-01-05 22:58 UTC by alegzandach

2021-01-05 23:00 UTC, alegzandach commented
This is where the google sheet lives https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0

2021-01-06 21:55 UTC, Lane commented
@alegzandach this is looking good! would you be able to add the script to fetch the language when running `npm run start` as well?

currently when i pull this branch and run `npm run start` i get an error because `en.js` does not exist:

```
Failed to compile.

./src/modules/explorer/app/selectors/lang.js
Module not found: Can't resolve '../constants/en' in '/Users/lane/Development/seda/map/src/modules/explorer/app/selectors'
```

2021-01-07 17:28 UTC, alegzandach commented
I just removed en.js from the gitignore instead of continuously generating a file that im assuming will generally be unchanging. Also re-added _old.

2021-01-07 18:01 UTC, Lane requested changes
thanks for that update, one last minor change and it should be good!

2021-01-07 19:04 UTC, alegzandach commented on package.json
> +    "node-fetch": "^2.6.1",
got it! done

2021-01-07 19:19 UTC, Lane approved these changes

2021-01-07 19:20 UTC, merged