Various fixes
Hyperobjekt/seda-map pull request #501
Opened 2021-01-22 23:33 UTC by touchRED

Closes #498, closes #480, fixes #499, fixes #479.

Viewable [here](https://focused-engelbart-a57f5e.netlify.app/).

Notes:
- Since we were forced to ditch the Mapbox geolocator and reimplement it using `flyToViewport`, activating geolocation **no longer displays a blue dot at the user's location**.
- Loading similar locations is now disabled for states, showing an explanatory tooltip on hover.

2021-01-25 18:51 UTC, Lane requested changes
geolocation looking good!

a few small touchups on the tooltip for `<CompareLoadSimilarButton />`:
- use the currently selected location to determine `region` from within the component, instead of passing a prop
- make sure any language in the explorer is not hardcoded and comes from the [explorer language google sheet](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0).

2021-01-25 18:51 UTC, Lane commented on src/modules/explorer/compare/components/CompareDialog.js
> +          <CompareLoadSimilarButton hideForStates={region === 'states'} />
no need for the `hideForStates` prop, the `CompareLoadSimilarButton` has the currently selected location data, which you can use to get the region

2021-01-25 18:51 UTC, Lane commented on src/modules/explorer/compare/components/CompareLoadSimilarButton.js
> +const CompareLoadSimilarButton = ({ hideForStates, ...props }) => {
remove `hideForStates` prop.  within the component use 

`const isStateLevel = getRegionForLocationId(selectedLocation)`

2021-01-25 18:51 UTC, Lane commented on src/modules/explorer/compare/components/CompareLoadSimilarButton.js
> +      title={hideForStates ? 'Loading similar regions is optimized for districts, counties, and schools.' : getLang('LOAD_SIMILAR_HINT', {
use the `isStateLevel` (from above) to determine which tooltip text.  also, do not hardcode this text, instead put the string in the [explorer language](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0) sheet with an associated key (e.g `LOAD_SIMILAR_STATES_HINT`)

2021-01-25 18:51 UTC, Lane commented on src/modules/explorer/compare/components/CompareLoadSimilarButton.js
> +          disabled={state.loaded || hideForStates}
use `isStateLevel` instead of `hideForStates` prop

2021-01-26 18:13 UTC, Lane requested changes
looks good, one more small change in regards to `useMemo`

2021-01-26 18:13 UTC, Lane commented on src/modules/explorer/compare/components/CompareLoadSimilarButton.js
> +  const isStateLevel = useMemo(() => locationData && getRegionFromLocationId(locationData.id) === 'states', [locationData])
this works, but we [don't need to use useMemo](https://kentcdodds.com/blog/usememo-and-usecallback#whats-the-point) here because:
- the computation of the `isStateLevel` boolean is not an expensive operation
- the resulting value of `isStateLevel` is a boolean, it has [referential equality](https://kentcdodds.com/blog/usememo-and-usecallback#referential-equality) to other boolean values (unlike objects / arrays)

2021-01-26 18:15 UTC, touchRED commented
@Lane: How's this?

`const isStateLevel = locationData && getRegionFromLocationId(locationData.id) === 'states'`

2021-01-26 18:17 UTC, Lane commented
@touchRED great, thanks!

2021-01-26 18:18 UTC, merged