implement slider redesign
Hyperobjekt/seda-map pull request #515
Opened 2021-01-28 22:22 UTC by touchRED

Closes #438.

Viewable [here](https://trusting-swirles-f53b8b.netlify.app/).

Notes:

- I'm a little disappointed in the implementation of the gradient – namely it just feels hacky to use pixel values for the color-stops. I tried using percentages but it seemed like there was no way for the percentages to be understood in terms of the parent element's sizing (even though root is styled `position: relative`. If you have any ideas to that end lmk.
- As always please tell me if something should/shouldn't be passed as a prop, if there's an easier way to do things using material-ui stuff I don't know about, etc.

2021-01-28 22:58 UTC, Lane requested changes
@touchRED this looks great! not too worried about pixel values for the gradient for now, if we need to switch widths at some point we can refactor some other time.

one change request, only the "active" educational opportunity metric should have the gradient (maximum 1).  e.g. when "Active Test Scores" is being viewed, only the "Active Test Scores Range" filter bar should have the gradient and all others should be blue.

if it's not too much of an ask, i think it would be good to override these styles in the `SedaMetricSlider.js` component, to keep business logic out of the shared components

2021-01-28 22:58 UTC, Lane commented on src/shared/components/Inputs/Slider.js
> +    background: (props) => props.metric === 'ses' ? 'currentColor' : 'fixed linear-gradient(90deg, #1C4E81 100px, #3A7BBB 139px, #7CB4DC 178px, #C0E1EC 217px, #F5F6F7 256px, #D6EECA 295px, #9FDCA3 33
given this is a shared component (in the `/shared` directory) we should try to keep business logic out of it. (e.g. anything specific to the explorer, like references to metrics or hardcoded values)

that way, we can use this component for other projects without having to modify source.  one way of doing this would be to add these styles overrides at the `SedaMetricSlider.js` level instead of in the shared slider.

2021-01-30 01:13 UTC, touchRED commented
@Lane thanks for the heads up – definitely makes sense to leave the shared component as-is. I moved the styles into `SedaMetricSlider`, and I was a little unsure of how to handle the gradient versus blue render without using a prop so I'm passing that down from `SedaFiltersForm` instead. It might be possible to remove or modify that class from within the component body, so lmk if that's what you'd like me to do. 

[Netlify link](https://trusting-swirles-f53b8b.netlify.app/) updated.

2021-01-30 03:07 UTC, Lane approved these changes

2021-01-30 03:08 UTC, Lane commented
@touchRED thanks, this looks sooo good! passing a prop works, you could also grab the active metric from within the component using the `useActiveOptions` hook, but i'm good either way.

2021-01-30 03:09 UTC, merged